use clap::{Arg, App};

pub fn get_arguments() -> App<'static, 'static> {
    App::new("gocd-encrypt")
        .version("0.1.1")
        .author("Alejandro Valdes <alejandrovaldes at live dot com>")
        .about("CLI to encrypt Strings using a remote gocd server")
        .arg(Arg::with_name("ANONYMOUS")
            .short("a")
            .long("anonymous-request")
            .help("Disables basic authentication")
            .takes_value(false))
        .arg(Arg::with_name("username")
            .short("u")
            .long("username")
            .help("username to login")
            .required_unless("ANONYMOUS")
            .takes_value(true))
        .arg(Arg::with_name("password")
            .short("p")
            .long("password")
            .help("password to login, if not specified will be asked from STDIN")
            .takes_value(true))
        .arg(Arg::with_name("INPUT")
            .help("String to encrypt")
            .required(true)
            .index(1))
        .arg(Arg::with_name("SERVER")
            .help("Server to connect to")
            .required(true)
            .index(2))
}